#!/usr/bin/env bash
# Configures Nginx to listen on port 80 and return Holberton School

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx start
