#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing "Ceci n'est pas une page"

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/a \    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /usr/share/nginx/html;\n        internal;\n    }' /etc/nginx/sites-available/default

if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
  sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
fi

service nginx restart
